name: generic-release

on:
  release:
    types: [published]

jobs:
  publishMacos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: macos
        run: |
          cmake ..
          make && sudo make install
        working-directory: ./build
      - name: Upload Macos Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./build/lib/libwebsockets.a
          asset_name: libwebsockets-macosX64.a
          asset_content_type: application/a
